---
title: "HW1 Applied Statistics/R"
author: "Svetlana Milrud"
date: "05 04 2022"
output:
  pdf_document: default
  html_document: default
---

```{r, include=FALSE}
library(ggplot2)
library(dplyr)
```

## Task

**Find the area of a figure bounded by curves given by the equation using the Monte Carlo method.**

Equations:

$$
 y = 2|x| - \pi, x \in [-{pi\over2},{pi\over2}]
$$
$$
 y = |sin(2x)|, x \in [-{pi\over 2},{pi\over 2}]
$$

## Generation of points

$$
 x \in [-{pi\over 2},{pi\over 2}];
$$ 

$$ 
 y \in [-\pi, 1]
$$

```{r}
trials <- 1000000
x <- runif(trials, min = -pi/2, max = pi/2)
y <- runif(trials, min = -pi, max = 1)
df <- data.frame(x,y)
montecarlo <- (y <= abs(sin(2*x))) & (y >= 2*abs(x) - pi)
```

```{r fig.align="center",fig.width = 14,fig.height=10}
ggplot(df) +
  geom_point(aes(x = x, y = y, color = montecarlo), size = 0.7) +
  theme_bw()
```

<br>

## Calculation of figure's area

```{r}
ratio <- sum(montecarlo) / trials
total <- (1 + pi) * (pi/2 + pi/2)
area <- ratio * total
cat(c('Area of a figure bounded by curves is equal to:', area))
```

<br>
<br>
